#!/bin/bash
set -eo pipefail

MODE="$(basename "$(dirname "$0")")"
ABI="$1"
IMAGE="$2"

exec </dev/null >&2
eval set -- "$DEB_MAINT_PARAMS"

# Workaround Rockchip U-Boot issue
# where they cannot load gzip compressed kernel image

if file /boot/vmlinuz-$ABI | grep -qi "gzip"
then
    mv /boot/vmlinuz-$ABI /boot/vmlinuz-$ABI.gz
    gunzip /boot/vmlinuz-$ABI.gz
fi
