#!/bin/bash
set -eo pipefail

MODE="$(basename "$(dirname "$0")")"
ABI="$1"
IMAGE="$2"

exec </dev/null >&2
eval set -- "$DEB_MAINT_PARAMS"
ACTION="$1"
VERSION="$2"

# Update EFI boot entries for systemd-boot

case $ACTION in
  configure|'') : ;;
  *) exit ;;
esac

if ! command -v efibootmgr >/dev/null
then
    exit
fi

echo "Updating /boot/efi/$(cat /etc/machine-id) ..."

case "$MODE" in
    postinst.d)
        if [[ -z "$IMAGE" ]]
        then
            IMAGE="$(ls /boot/vmlinu*-$ABI)"
        fi
        kernel-install add "$ABI" "$IMAGE"
        ;;
    postrm.d)
        kernel-install remove "$ABI"
        ;;
    sbin)
        ;;
esac
