#!/bin/bash
set -eo pipefail

MODE="$(basename "$(dirname "$0")")"
ABI="$1"
IMAGE="$2"

exec </dev/null >&2
eval set -- "$DEB_MAINT_PARAMS"
ACTION="$1"
VERSION="$2"

# Update EFI boot entries for systemd-boot

if ! command -v efibootmgr >/dev/null
then
    exit
fi

case $ACTION in
    configure)
        echo "Updating EFI entry for $ABI ..."
        if [[ -z "$IMAGE" ]]
        then
            IMAGE="$(ls /boot/vmlinu*-$ABI)"
        fi
        kernel-install add "$ABI" "$IMAGE"
        ;;
    remove)
        echo "Removing EFI entry for $ABI ..."
        kernel-install remove "$ABI"
        ;;
esac
