#!/bin/bash
set -euo pipefail

# shellcheck disable=SC2034
MODE="$(basename "$(dirname "$0")")"
ABI="$1"
IMAGE="$2"

exec </dev/null >&2
eval set -- "$DEB_MAINT_PARAMS"
ACTION="$1"
# shellcheck disable=SC2034
VERSION="$2"

# Update EFI boot entries for systemd-boot

if ! command -v efibootmgr >/dev/null
then
    exit
fi

case $ACTION in
    configure)
        echo "Updating EFI entry for $ABI ..."
        if [[ -z "$IMAGE" ]]
        then
            KERNELS=(/boot/vmlinu*-"$ABI")
            IMAGE="${KERNELS[0]}"
        fi
        kernel-install add "$ABI" "$IMAGE"
        ;;
    remove)
        echo "Removing EFI entry for $ABI ..."
        kernel-install remove "$ABI"
        ;;
esac
