#!/bin/bash
set -eo pipefail

MODE="$(basename "$(dirname "$0")")"
ABI="$1"
IMAGE="$2"

exec </dev/null >&2
eval set -- "$DEB_MAINT_PARAMS"
ACTION="$1"
VERSION="$2"

# Update extlinux.conf

case $ACTION in
    configure|remove|'') : ;;
    *) exit ;;
esac

if ! source /etc/default/extlinux 2>/dev/null
then
    exit
fi

echo "Updating /boot/extlinux/extlinux.conf ..."

TIMEOUT=${TIMEOUT:-3}
APPEND="$(cat /etc/kernel/cmdline)${APPEND:+ $APPEND}"

mkdir -p /boot/extlinux/
cat << EOF > /boot/extlinux/extlinux.conf.new
timeout $TIMEOUT
menu title Radxa Boot Selection
#default $DEFAULT

EOF

if [[ -n "$DEFAULT" ]]
then
    sed -i "s/^#default/default/" /boot/extlinux/extlinux.conf.new
fi

mkdir -p /boot/dtbs.new

while read
do
    cp -au "/usr/lib/linux-image-$REPLY" "/boot/dtbs.new/$REPLY"
    cat << EOF >> /boot/extlinux/extlinux.conf.new
label $REPLY
    kernel /boot/vmlinuz-$REPLY
    initrd /boot/initrd.img-$REPLY
    devicetreedir /boot/dtbs/$REPLY
    #fdtoverlays ${FDTOVERLAYS[*]/#/\/boot\/dtbs\/$REPLY\/}
    append $APPEND

EOF
done < <(linux-version list | linux-version sort --reverse)

if (( ${#FDTOVERLAYS[@]} != 0 ))
then
    sed -i "s/#fdtoverlays/fdtoverlays/g" /boot/extlinux/extlinux.conf.new
fi

mv /boot/extlinux/extlinux.conf.new /boot/extlinux/extlinux.conf
rm -rf /boot/dtbs
mv /boot/dtbs.new /boot/dtbs
